"""Python-first explainability tools for native two-dimensional ViTs."""

from .artifacts import load_explanation, save_explanation
from .evaluation import (
    Completeness,
    DeletionInsertion,
    EvaluationMetric,
    Infidelity,
    Localization,
    ParameterRandomizationSanity,
    SaCo,
    Sensitivity,
)
from .explainer import ViTExplainer
from .methods import (
    AttentionRollout,
    AttributionMethod,
    GradientAttentionRollout,
    InputXGradient,
    IntegratedGradients,
    LayerGradCAM,
    LeGrad,
    PatchOcclusion,
    RawAttention,
    Saliency,
    SmoothGrad,
)
from .types import (
    ActivationAtlas,
    EvaluationReport,
    Explanation,
    ForwardArgs,
    Intervention,
    InterventionResult,
    InterventionSite,
    LayerTrace,
    MetricResult,
    MLPTrace,
    TokenLayout,
    TraceConfig,
    ViTTrace,
)
from .visualization import interpolate_token_attribution, normalize_attribution


__all__ = [
    "ActivationAtlas",
    "AttentionRollout",
    "AttributionMethod",
    "Completeness",
    "DeletionInsertion",
    "EvaluationReport",
    "EvaluationMetric",
    "Explanation",
    "ForwardArgs",
    "GradientAttentionRollout",
    "InputXGradient",
    "IntegratedGradients",
    "Infidelity",
    "interpolate_token_attribution",
    "Intervention",
    "InterventionSite",
    "InterventionResult",
    "LayerTrace",
    "LayerGradCAM",
    "LeGrad",
    "Localization",
    "MLPTrace",
    "MetricResult",
    "ParameterRandomizationSanity",
    "PatchOcclusion",
    "RawAttention",
    "load_explanation",
    "Saliency",
    "SaCo",
    "Sensitivity",
    "save_explanation",
    "SmoothGrad",
    "normalize_attribution",
    "TokenLayout",
    "TraceConfig",
    "ViTExplainer",
    "ViTTrace",
]
